# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: certinfo

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: certinfo
    main: ./main.go
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  - name: certinfo
    repository:
      owner: marco-introini
      name: homebrew-tap
    homepage: https://github.com/marco-introini/certinfo
    description: CLI tool to analyze X.509 certificates and private keys
    license: MIT
    ids:
      - certinfo
    download_strategy: GithubRelease
    commit_author:
      name: marco-introini
      email: marco@marcointroini.it
    directory: Formula
    install: |
      bin.install "certinfo"
    test: |
      system "#{bin}/certinfo", "--help"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
